### PR TITLE
[i18n] translate Spanish

### PR DESCRIPTION
**Pull request by Nadai2010**
### Description
Hi team, i add translation version Spanish

### CODE REVIEW

**Comment by julio4** [comment]
LGTM! Thank you very much.
Please review my comments in #133 but I believe you have already.

**Comment by Nadai2010** [comment]
Hello @julio4 Sorry for not answering, I just put 👍 in #133. 

I agree to update the book every 15 - 30 days, if at any time you have a important update, you can tag us to know what is important and give priority if we can compared to the period of 15 to 30 days that we mentioned.

By the way: @cryptonerdcn  or @julio4, I'm checking, did I miss any settings? I don't see the Spanish version added.

Very Thank you

**Comment by Nadai2010** [comment]
Normally I only upload the po.es, but when creating the language from 0, I did the pr to update the message.pot and I don't know why the po.ch was updated, I didn't touch anything there 😅, sorry @cryptonerdcn

**Comment by cryptonerdcn** [comment]
> Normally I only upload the po.es, but when creating the language from 0, I did the pr to update the message.pot and I don't know why the po.ch was updated, I didn't touch anything there 😅, sorry @cryptonerdcn

That's OK. Next time you can just commit `es.po ` and reset `zh-cn.po` to default. It will work.

**Comment by julio4** [comment]
@cryptonerdcn @Nadai2010 Thank you both for the reactivity!

There's still an issue with the Spanish version @Nadai2010, where some parts are not translated well. Could you look into it?

**Comment by Nadai2010** [comment]
Hi @julio4, I upload it in this PR #147, I don't know what happened but the file was broken, everything is corrected now.

Thank You

**Pull request merged**
