### PR TITLE
Feat: hashing

### LINKED ISSUE #69: feat: Hash trait
Show an example that use `#[derive(Hash)]` to hash an user defined type.
Show how to use different hashing functions: Poseidon and Pedersen.

See [here](https://community.starknet.io/t/cairo-v2-2-0-is-out/99263#hash) for documentation

### PR DESCRIPTION
**Pull request by julio4**
**Issue(s):** Close #69, #159, #160

### CODE REVIEW

**Comment by julio4** [comment]
@OkoliEvans @fontanellag I merged your two PRs and made minor modifications. Both contributions were valuable. Let me know if you agree with the result

**Comment by fontanellag** [comment]
> @OkoliEvans @fontanellag I merged your the two PRs and made minor modifications. Both contributions were valuable. Let me know if you agree with the result
Great. Thanks!

**Comment by OkoliEvans** [comment]
I'm totally cool with it. :D

**Comment by OkoliEvans** [comment]
> @OkoliEvans @fontanellag I merged your the two PRs and made minor modifications. Both contributions were valuable. Let me know if you agree with the result

I'm totally cool with it :D

**Pull request merged**
