### PR TITLE
Commit reveal #77

### LINKED ISSUE #77: feat: Commit-Reveal scheme

### PR DESCRIPTION
**Pull request by LamsyA**
**Issue(s):** Close #77 

### Description

This is an implementation of the commitment scheme in cairo.

The contract uses a commitment scheme where bidders first commit to their bids and later reveal them. This ensures bid privacy until the reveal phase.

Interface: **_ICommitmentRevealTrait_**
The **_ICommitmentRevealTrait_** interface defines two essential methods:

commit(name: felt252, amount: felt252) -> felt252: Commits a bid with a name and amount, returning a hash.
reveal(name: felt252, amount: felt252) -> bool: Reveals a previously committed bid, returning true if the commitment is valid.

### Checklist

- [x] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [x] **Contract Tests:** Added tests to cover the changes

### CODE REVIEW

**Review by julio4 — CHANGES_REQUESTED** [review]
The implementation does not fully conform to the commit-reveal scheme. The hash of the "secret", let's say `x`, should be computed off-chain, and the resulting hash should be used on-chain as an "attestation" that the user has committed to this value `x`, noted as `commitment = hash(x)`. At the time of the commitment, the value `x` is kept secret while the commitment is made public.

Later, the user can reveal `y`, and the contract can verify that the revealed value `y` matches the committed value `x` by checking that `hash(y) == commitment`. This ensures that `x == y`.

A simple example could be the submission of a secret message, that can be optionally revealed at a later time with the guarantee that it was written at the time of commitment.

**Comment by LamsyA** [comment]
Okay, am on it.

**Comment by julio4** [comment]
@LamsyA Hello, did you have the time to review and apply the changes in the last comments? Let me know if you need help.

**Comment by LamsyA** [comment]
> @LamsyA Hello, did you have the time to review and apply the changes in the last comments? Let me know if you need help.

Yeah, I did

I might need your help to clarify something.

**Comment by julio4** [comment]
> > @LamsyA Hello, did you have the time to review and apply the changes in the last comments? Let me know if you need help.
> 
> Yeah, I did
> 
> I will need your help to clarify something.

Yes, what points you would like me to clarify?

**Comment by LamsyA** [comment]
I have corrected the code;

- Commitment Phase:

   -  Off-chain: Compute the hash of the secret value.

   - On-chain: Store the hash (commitment).

- Reveal Phase:

     - On-chain: Submit the original secret value.

    - On-chain: Verify that the hash of the submitted secret matches the stored commitment.

 you can now review it.

**Comment by LamsyA** [comment]
Hi @julio4, kindly review this PR.

**Review by julio4 — APPROVED** [review]

**Review by julio4 — APPROVED** [review]
Changed to a simpler example and write the `.md` file

**Pull request merged**
