### PR TITLE
[i18n]zh-cn minor fix

### PR DESCRIPTION
**Pull request by cryptonerdcn**
**Issue(s):** 

### Description

Fix typos.

### Checklist

- [ ] **CI Verifier:** Run `cairo_programs_verifier` successfully
- [ ] **Contract Tests:** Added tests to cover the changes
- [ ] **Remix Link:** Added a link to open the contract in Remix
- [ ] **Deployed Contract (Optional):** If possible, include a Voyager link to a deployed contract on Goerli

### CODE REVIEW

**Comment by cryptonerdcn** [comment]
@julio4 Yes it breaks sths but not too many. Most of them are links.
I will rebase and fix it.

**Comment by cryptonerdcn** [comment]
@julio4 Finished. We will translate the `components` chapter next week(because I am translating the `components` chapter of Cairo Book :p)

**Comment by Nadai2010** [comment]
I think @cryptonerdcn or I should upload the updated message.pot, I checked their new translation file zh-cn.po, and I think the merge will break it just like what's happening in Spanish.

**Comment by julio4** [comment]
Did you encounter the same errors in the Cairo book? I can try to downgrade mdbook to 0.4.31.
I'll need to read the i18n documentation. Feel free to open an issue and continue the discussion there.

**Comment by cryptonerdcn** [comment]
@julio4 Yes, also in Cairo Book, dojobook and starknetbook. They all have same issue now.

**Comment by cryptonerdcn** [comment]
@julio4 Maybe we can merge this first.

**Pull request merged**
