### PR TITLE
fix: chapter-related folder names

### PR DESCRIPTION
**Pull request by raizo07**
**Issue(s):** 

### Description

Renamed folder names to the standard related names.

### Checklist

- [ ] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [ ] **Contract Tests:** Added tests to cover the changes

### CODE REVIEW

**Review by misicnenad — CHANGES_REQUESTED** [review]
Don't forget to update all of the references within *.md* files as well, they're currently broken

**Comment by raizo07** [comment]
> Don't forget to update all of the references within _.md_ files as well, they're currently broken

@misicnenad I've fixed them

**Review by misicnenad — APPROVED** [review]

**Comment by misicnenad** [comment]
@julio4 pinging you to check the PR out yourself, all seems good

**Comment by misicnenad** [comment]
@raizo07 please resolve the conflicts, so that the branch can be merged

**Comment by raizo07** [comment]
@misicnenad @julio4 Merge conflict resolved

**Review by julio4 — APPROVED** [review]

**Pull request merged**
