### PR TITLE
add time locked transactions example

### LINKED ISSUE #190: Feature: Time locked transactions
### Description

In this example, we will show how to implement a contract that takes transactions. After a minimum `waitPeriod`, the locked transaction(s) can be executed.

### Criteria:

- Include comprehensive tests
- Deploy the contract on a testnet

### Ressources:

- [Solidity By Example - Time Lock](https://solidity-by-example.org/app/time-lock/)

### ODHack

To be eligible for additional rewards, be sure to review and follow the [ODHack Common Guidelines](https://www.notion.so/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f?pvs=21) and [Contributing Guidelines](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#contributing).
Be sure to join the telegram group and introduce yourself.

### PR DESCRIPTION
**Pull request by saimeunt**
**Issue(s):** Close #190 

### Description

This PR introduces a new application example named `TimeLock` which is the Cairo adaptation of the corresponding [Solidity by Example contract](https://solidity-by-example.org/app/time-lock/).
Tests have been added to make sure the implementation is correct using a dummy `ERC721` and execute a `transfer_from` on the token from the `TimeLock` contract and make sure it is executable only after the wait period is over.

Screenshot 2024-05-29 at 23 54 43

### Checklist

- [X] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [X] **Contract Tests:** Added tests to cover the changes

### CODE REVIEW

**Comment by saimeunt** [comment]
@julio4 I added a commit to install snforge in the GH action using https://github.com/marketplace/actions/setup-starknet-foundry

The `compile_and_verify` workflow is now successful on my own fork:

Screenshot 2024-05-31 at 23 37 25

**Review by julio4 — APPROVED** [review]
LGTM! Some suggestions in comments, let me know what you think!

**Comment by saimeunt** [comment]
@julio4 I've made the requested changes, please review 👍

**Review by julio4 — APPROVED** [review]
LGTM!

**Pull request merged**
