### PR TITLE
Account Abstraction - Spending Limits

### LINKED ISSUE #230: Feature: Account Abstraction - Spending Limits
I thought I could create a Cairo contract and a content about Account Abstraction on Starknet. Spending/withdrawal limits for Starknet accounts for ERC-20 tokens could be added, and the developers could learn more about how to write their own account contracts on Starknet with Starknet By Example website. Do you think it is a good idea to add this feature on Starknet By Example?

### PR DESCRIPTION
**Pull request by egeaybars123**
**Issue(s):** Close #230 

### Description

Account Contract with Spending Limits for any ERC20 token.

### Checklist

- [ ] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [x] **Contract Tests:** Added tests to cover the changes

### CODE REVIEW

**Comment by julio4** [comment]
Hello @egeaybars123, do you want to continue working on this, or should I edit the last few changes by myself?

**Comment by egeaybars123** [comment]
> Hello @egeaybars123, do you want to continue working on this, or should I edit the last few changes by myself?

Hey @julio4, I can work on those changes if you could please provide me with the feedback.

**Comment by julio4** [comment]
> > Hello @egeaybars123, do you want to continue working on this, or should I edit the last few changes by myself?
> 
> Hey @julio4, I can work on those changes if you could please provide me with the feedback.

My bad, I started a review and forgot to finish it. Let me finish it soon.

**Comment by julio4** [comment]
@egeaybars123 The repository has been upgraded to a new site generator and the Markdown format to include code listings is slightly different. The [CONTRIBUTING](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md) guidelines has been updated to reflect these changes.
Could you rebase this PR onto `dev`. If there's any issues or if you want me to do these changes let me know.

**Comment by egeaybars123** [comment]
Hey @julio4, I am currently working on different things. I'd be really glad if you could make those changes! Have a great week.

**Comment by julio4** [comment]
I'll close this in favor of #277
Feel free to review it if needed

**Pull request closed without merging**
